# Generated by Django 4.1 on 2022-08-08 17:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('fathers_name', models.CharField(max_length=50)),
                ('mothers_name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('students_aadhar_number', models.IntegerField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('dob', models.DateField()),
                ('Address', models.CharField(max_length=300)),
                ('doj', models.DateField()),
                ('id_card', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('standard', models.IntegerField(blank=True, default=0)),
                ('School_name', models.CharField(blank=True, default='None', max_length=200)),
                ('school_category', models.CharField(choices=[('G', 'Government'), ('P', 'Private')], default='G', max_length=1)),
                ('Medium', models.CharField(choices=[('E', 'English'), ('H', 'Hindi'), ('O', 'Other')], default='Hindi', max_length=1)),
                ('Signature', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Volunteer_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email_address', models.EmailField(max_length=254)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('doj', models.DateField()),
                ('preferred_Centre', models.CharField(choices=[('S45', 'Sector 45'), ('S15', 'Sector 15 part 2'), ('S14', 'Sector 14')], max_length=3)),
                ('id_card', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('student_enrolled', models.ManyToManyField(blank=True, to='Alankaarsite.student_new')),
            ],
        ),
    ]
